name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 11.6.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^7.0.3
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  speech_to_text: ^6.6.0

  # FIREBASE
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  cloud_firestore: ^5.0.0
  firebase_pagination: ^4.0.0

  # FIREBASE MESSAGING
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2

  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # ICON
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.10+1

  # IMAGE
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  lottie: ^3.1.2

  # OTHER
  country_picker: ^2.0.26
  flutter_custom_tabs: ^2.0.0+1
  permission_handler: ^11.3.1
  flutter_html: ^3.0.0-beta.2

  webview_flutter: ^4.8.0
  file_picker: 8.0.4

  # SOCIAL LOGIN
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  # PAYMENT GATEWAYS
  midpay: ^1.1.7
  phonepe_payment_sdk: ^2.0.1
  qr_flutter: ^4.1.0 #required for in pix_flutter
  pix_flutter: ^2.2.0
  razorpay_flutter: ^1.3.7
  flutterwave_standard: ^1.0.8
  flutter_stripe: ^10.1.1
  cinetpay: ^1.0.7
  flutter_paypal_checkout:
    git:
      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
      ref: 1.0.0

  # MAP
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  crypto: 3.0.3 #required for in phonepe

  flutter_localizations:
    sdk: flutter
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/upi_payment/
    - assets/lottie/
    - assets/newDashboard/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

